version: '3'
services:
  backend:
    image: meraki-backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://meraki:meraki1@atlascluster.dzlwgg7.mongodb.net/?retryWrites=true&w=majority
      # Add any other environment variables your backend needs

  frontend:
    image: meraki-frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://backend:5000 # Use the service name defined above
    depends_on:
      - backend